// Comprehensive Art Courses for Beginners to Experts
export const artistCourses = [
  // === COMPREHENSIVE ART: BEGINNER TO EXPERT ===
  // Absolute Beginner
  {
    id: 107,
    title: "Art Basics: Getting Started",
    description: "For complete beginners: materials, tools, mindset, and overcoming creative blocks.",
    level: "beginner",
    duration: "2 hours",
    students: 12400,
    rating: 4.9,
    tags: ["Art Fundamentals", "Beginner", "Getting Started"],
    icon: "🎨",
  },
  {
    id: 108,
    title: "Observational Drawing",
    description: "Draw from life: still life, portraits, landscapes, and improving visual perception.",
    level: "beginner",
    duration: "3.5 hours",
    students: 7800,
    rating: 4.8,
    tags: ["Drawing", "Observation", "Fundamentals"],
    icon: "👀",
  },
  
  // Core Fundamentals (Beginner)
  {
    id: 109,
    title: "Shape & Form Basics",
    description: "Master basic shapes: circles, cubes, spheres, and constructing complex forms.",
    level: "beginner",
    duration: "3 hours",
    students: 8900,
    rating: 4.8,
    tags: ["Drawing", "Form", "Fundamentals"],
    icon: "⭕",
  },
  {
    id: 110,
    title: "Shading & Value Studies",
    description: "Understand light and shadow: creating dimension, depth, and realistic rendering.",
    level: "beginner",
    duration: "4 hours",
    students: 7500,
    rating: 4.8,
    tags: ["Shading", "Value", "Drawing"],
    icon: "🖼️",
  },
  {
    id: 111,
    title: "Composition & Rule of Thirds",
    description: "Create balanced artworks: leading lines, focal points, and dynamic compositions.",
    level: "beginner",
    duration: "3 hours",
    students: 6800,
    rating: 4.8,
    tags: ["Composition", "Design", "Fundamentals"],
    icon: "📐",
  },

  // Intermediate Fundamentals
  {
    id: 112,
    title: "Advanced Perspective (1-2-3 Point)",
    description: "Master all perspective systems: architectural, environmental, and depth tricks.",
    level: "intermediate",
    duration: "5 hours",
    students: 5600,
    rating: 4.8,
    tags: ["Perspective", "Drawing", "Technique"],
    icon: "🏢",
  },
  {
    id: 113,
    title: "Color Theory Masterclass",
    description: "Complete color science: mixing, harmony, temperature, saturation, and psychology.",
    level: "intermediate",
    duration: "5 hours",
    students: 6200,
    rating: 4.9,
    tags: ["Color", "Theory", "Art"],
    icon: "🌈",
  },

  // Character Drawing & Design
  {
    id: 114,
    title: "Basic Figure Drawing",
    description: "Draw human figures: proportions, gesture, dynamic poses, and anatomy basics.",
    level: "beginner",
    duration: "4.5 hours",
    students: 7200,
    rating: 4.8,
    tags: ["Figure", "Drawing", "Anatomy"],
    icon: "🧍",
  },
  {
    id: 115,
    title: "Advanced Character Anatomy",
    description: "Deep dive: skeletal structure, muscle groups, movement, and diverse body types.",
    level: "advanced",
    duration: "7 hours",
    students: 4100,
    rating: 4.9,
    tags: ["Anatomy", "Character", "Advanced"],
    icon: "💀",
  },
  {
    id: 116,
    title: "Facial Features & Expressions",
    description: "Master faces: eye, nose, mouth construction, expressions, and emotion.",
    level: "intermediate",
    duration: "4.5 hours",
    students: 6500,
    rating: 4.8,
    tags: ["Faces", "Expression", "Drawing"],
    icon: "😊",
  },
  {
    id: 117,
    title: "Hair, Clothing & Accessories",
    description: "Draw realistic hair types, fabric folds, and detailed costume design.",
    level: "intermediate",
    duration: "4 hours",
    students: 5300,
    rating: 4.7,
    tags: ["Hair", "Clothing", "Details"],
    icon: "👗",
  },

  // Digital Art Software
  {
    id: 118,
    title: "Procreate Essentials for Beginners",
    description: "Start iPad painting: interface, brushes, layers, and basic digital painting.",
    level: "beginner",
    duration: "3 hours",
    students: 5800,
    rating: 4.8,
    tags: ["Procreate", "iPad", "Digital Art"],
    icon: "📱",
  },
  {
    id: 119,
    title: "Procreate Advanced Techniques",
    description: "Advanced Procreate: animation assist, 3D painting, effects, and speed painting.",
    level: "advanced",
    duration: "5 hours",
    students: 3400,
    rating: 4.8,
    tags: ["Procreate", "Advanced", "Digital Art"],
    icon: "📱",
  },
  {
    id: 120,
    title: "Clip Studio Paint Beginner to Pro",
    description: "Professional manga & comic art: tools, 3D models, animation, and effects.",
    level: "intermediate",
    duration: "6 hours",
    students: 4900,
    rating: 4.8,
    tags: ["Clip Studio Paint", "Digital Art", "Comics"],
    icon: "🖌️",
  },
  {
    id: 121,
    title: "Photoshop for Digital Artists",
    description: "Advanced Photoshop: painting, retouching, compositing, and photo manipulation.",
    level: "intermediate",
    duration: "6.5 hours",
    students: 6100,
    rating: 4.8,
    tags: ["Photoshop", "Digital Art", "Retouching"],
    icon: "🎨",
  },

  // Digital Painting Styles
  {
    id: 122,
    title: "Digital Painting: Realistic Rendering",
    description: "Hyper-realistic digital painting: textures, lighting, and photo-realistic effects.",
    level: "advanced",
    duration: "6 hours",
    students: 3800,
    rating: 4.8,
    tags: ["Digital Painting", "Realistic", "Advanced"],
    icon: "✨",
  },
  {
    id: 123,
    title: "Stylized Digital Painting",
    description: "Cartoon, anime, and stylized painting: expressive brushwork and color.",
    level: "intermediate",
    duration: "5 hours",
    students: 5200,
    rating: 4.8,
    tags: ["Digital Painting", "Stylized", "Art"],
    icon: "🎨",
  },
  {
    id: 124,
    title: "Oil Painting Simulation in Digital",
    description: "Digital oil painting techniques: brushwork, blending, and texture simulation.",
    level: "intermediate",
    duration: "4.5 hours",
    students: 4100,
    rating: 4.7,
    tags: ["Digital Painting", "Oil", "Technique"],
    icon: "🖼️",
  },

  // Traditional Art (Comprehensive)
  {
    id: 125,
    title: "Watercolor Fundamentals",
    description: "Watercolor basics: washes, transparency, glazing, and wet-on-wet techniques.",
    level: "beginner",
    duration: "4 hours",
    students: 5600,
    rating: 4.8,
    tags: ["Watercolor", "Traditional", "Painting"],
    icon: "💧",
  },
  {
    id: 126,
    title: "Oil Painting Mastery",
    description: "Oil painting: underpainting, glazing, impasto, and professional techniques.",
    level: "intermediate",
    duration: "6 hours",
    students: 4200,
    rating: 4.8,
    tags: ["Oil Painting", "Traditional", "Advanced"],
    icon: "🖼️",
  },
  {
    id: 127,
    title: "Acrylic Painting Techniques",
    description: "Fast-drying acrylics: layering, texture, mixed media, and flexible approach.",
    level: "intermediate",
    duration: "4 hours",
    students: 4800,
    rating: 4.7,
    tags: ["Acrylic", "Traditional", "Painting"],
    icon: "🎨",
  },
  {
    id: 128,
    title: "Charcoal & Graphite Drawing",
    description: "Graphite pencils and charcoal: blending, pressure control, and advanced shading.",
    level: "intermediate",
    duration: "4 hours",
    students: 5100,
    rating: 4.8,
    tags: ["Charcoal", "Graphite", "Drawing"],
    icon: "✏️",
  },
  {
    id: 129,
    title: "Ink & Pen Art",
    description: "Pen & ink techniques: stippling, hatching, crosshatching, and ink effects.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 4600,
    rating: 4.8,
    tags: ["Ink", "Pen", "Drawing"],
    icon: "🖊️",
  },

  // Specialization: Character Art
  {
    id: 130,
    title: "Character Design: From Concept to Final",
    description: "Complete character pipeline: sketching, iteration, final design, and variations.",
    level: "advanced",
    duration: "6.5 hours",
    students: 4300,
    rating: 4.9,
    tags: ["Character Design", "Advanced", "Art"],
    icon: "👤",
  },
  {
    id: 131,
    title: "Character Modeling & 3D Sculpting",
    description: "3D character creation: blocking, sculpting, retopology, and UV mapping.",
    level: "advanced",
    duration: "7 hours",
    students: 3200,
    rating: 4.8,
    tags: ["3D", "Character", "Sculpting"],
    icon: "🗿",
  },

  // Specialization: Environment Art
  {
    id: 132,
    title: "Landscape Fundamentals",
    description: "Paint landscapes: atmosphere, weather, lighting, and environmental mood.",
    level: "intermediate",
    duration: "5 hours",
    students: 5100,
    rating: 4.8,
    tags: ["Landscape", "Environment", "Painting"],
    icon: "🏔️",
  },
  {
    id: 133,
    title: "Environment Design for Games & Film",
    description: "Create game environments: modular design, optimization, and storytelling.",
    level: "advanced",
    duration: "6.5 hours",
    students: 3800,
    rating: 4.8,
    tags: ["Environment", "Game Design", "Professional"],
    icon: "🏙️",
  },

  // Specialization: Illustration
  {
    id: 134,
    title: "Book Illustration",
    description: "Create illustrations for books: layout, narrative, typography integration.",
    level: "intermediate",
    duration: "5 hours",
    students: 4100,
    rating: 4.8,
    tags: ["Illustration", "Publishing", "Art"],
    icon: "📖",
  },
  {
    id: 135,
    title: "Concept Art Fundamentals",
    description: "Design exploration: rapid ideation, multiple concepts, and visual development.",
    level: "intermediate",
    duration: "5 hours",
    students: 4700,
    rating: 4.8,
    tags: ["Concept Art", "Design", "Professional"],
    icon: "🎨",
  },
  {
    id: 136,
    title: "Storyboarding for Film & Animation",
    description: "Visual storytelling: layout, composition, and cinematic panels.",
    level: "intermediate",
    duration: "4.5 hours",
    students: 3800,
    rating: 4.8,
    tags: ["Storyboarding", "Film", "Narrative"],
    icon: "📹",
  },

  // Animation & Motion
  {
    id: 137,
    title: "2D Animation: Beginner to Intermediate",
    description: "Frame-by-frame animation: timing, spacing, walk cycles, and expressions.",
    level: "intermediate",
    duration: "6 hours",
    students: 4200,
    rating: 4.8,
    tags: ["2D Animation", "Motion", "Art"],
    icon: "🎬",
  },
  {
    id: 138,
    title: "3D Character Animation",
    description: "Rigging and animating 3D characters: walk cycles, actions, and polish.",
    level: "advanced",
    duration: "7 hours",
    students: 3100,
    rating: 4.8,
    tags: ["3D Animation", "Character", "Advanced"],
    icon: "🎞️",
  },

  // 3D Art (Comprehensive)
  {
    id: 139,
    title: "Blender: Complete 3D Beginner Course",
    description: "Start 3D: interface, modeling, materials, lighting, and rendering basics.",
    level: "beginner",
    duration: "6 hours",
    students: 6200,
    rating: 4.8,
    tags: ["Blender", "3D", "Beginner"],
    icon: "🟠",
  },
  {
    id: 140,
    title: "Hard Surface Modeling in Blender",
    description: "Model mechanical objects: vehicles, weapons, architecture with precision.",
    level: "intermediate",
    duration: "5.5 hours",
    students: 3900,
    rating: 4.8,
    tags: ["Blender", "Modeling", "Hard Surface"],
    icon: "⚙️",
  },
  {
    id: 141,
    title: "Organic Sculpting in Blender",
    description: "Digital sculpting: creatures, characters, and organic forms.",
    level: "intermediate",
    duration: "5.5 hours",
    students: 4100,
    rating: 4.8,
    tags: ["Blender", "Sculpting", "Organic"],
    icon: "🗿",
  },
  {
    id: 142,
    title: "Texturing & Materials Mastery",
    description: "Create realistic textures: PBR workflows, normal maps, and material blending.",
    level: "advanced",
    duration: "6 hours",
    students: 3500,
    rating: 4.8,
    tags: ["Texturing", "Materials", "3D"],
    icon: "🎨",
  },
  {
    id: 143,
    title: "Lighting & Rendering in Blender",
    description: "Professional lighting: HDRI, volumetrics, rendering engines, and optimization.",
    level: "advanced",
    duration: "5.5 hours",
    students: 3200,
    rating: 4.8,
    tags: ["Lighting", "Rendering", "3D"],
    icon: "💡",
  },

  // Photography
  {
    id: 144,
    title: "Photography Fundamentals",
    description: "Master exposure, composition, and fundamentals with any camera.",
    level: "beginner",
    duration: "4 hours",
    students: 6500,
    rating: 4.8,
    tags: ["Photography", "Fundamentals", "Beginner"],
    icon: "📷",
  },
  {
    id: 145,
    title: "Portrait Photography & Lighting",
    description: "Portrait lighting setups: studio, natural light, and flattering techniques.",
    level: "intermediate",
    duration: "4.5 hours",
    students: 4800,
    rating: 4.8,
    tags: ["Photography", "Portraits", "Lighting"],
    icon: "👤",
  },
  {
    id: 146,
    title: "Photoshop Retouching & Post-Processing",
    description: "Professional retouching: skin, liquify, color grading, and advanced editing.",
    level: "advanced",
    duration: "6 hours",
    students: 3900,
    rating: 4.8,
    tags: ["Photography", "Retouching", "Post-Processing"],
    icon: "✨",
  },

  // Vector & Graphic Design
  {
    id: 147,
    title: "Adobe Illustrator Fundamentals",
    description: "Vector graphics basics: shapes, bezier curves, pathfinding, and typography.",
    level: "beginner",
    duration: "4 hours",
    students: 5400,
    rating: 4.8,
    tags: ["Illustrator", "Vector Art", "Design"],
    icon: "✨",
  },
  {
    id: 148,
    title: "Advanced Vector Illustration",
    description: "Professional vector illustration: complex artwork, effects, and branding.",
    level: "advanced",
    duration: "5.5 hours",
    students: 3100,
    rating: 4.8,
    tags: ["Vector Art", "Illustration", "Professional"],
    icon: "✨",
  },
  {
    id: 149,
    title: "Logo Design Essentials",
    description: "Create memorable logos: symbolism, versatility, scalability, and branding.",
    level: "intermediate",
    duration: "4 hours",
    students: 5800,
    rating: 4.9,
    tags: ["Logo Design", "Branding", "Design"],
    icon: "🔷",
  },

  // Specialist Topics
  {
    id: 150,
    title: "Visual Effects (VFX) for Film",
    description: "Advanced VFX: compositing, keying, tracking, and professional effects.",
    level: "advanced",
    duration: "7 hours",
    students: 2800,
    rating: 4.8,
    tags: ["VFX", "Film", "Advanced"],
    icon: "✨",
  },
  {
    id: 151,
    title: "Motion Graphics: After Effects Mastery",
    description: "Professional motion design: keyframes, plugins, sound design, and exports.",
    level: "advanced",
    duration: "7 hours",
    students: 3200,
    rating: 4.8,
    tags: ["Motion Graphics", "After Effects", "Professional"],
    icon: "🎬",
  },

  // Career & Professional Development
  {
    id: 152,
    title: "Building an Art Portfolio",
    description: "Create professional portfolio: selection, presentation, and marketing.",
    level: "intermediate",
    duration: "3 hours",
    students: 4100,
    rating: 4.9,
    tags: ["Career", "Portfolio", "Professional"],
    icon: "📁",
  },
  {
    id: 153,
    title: "Art Industry Career Paths",
    description: "Explore careers: game dev, film, animation, freelance, and opportunities.",
    level: "beginner",
    duration: "2.5 hours",
    students: 5300,
    rating: 4.8,
    tags: ["Career", "Industry", "Guide"],
    icon: "🚀",
  },
  {
    id: 154,
    title: "Freelance Artist Business Guide",
    description: "Run your art business: pricing, contracts, marketing, and client management.",
    level: "intermediate",
    duration: "4 hours",
    students: 3800,
    rating: 4.8,
    tags: ["Freelance", "Business", "Career"],
    icon: "💼",
  },
  {
    id: 155,
    title: "Social Media for Artists",
    description: "Build audience: Instagram, Twitter, TikTok, and monetizing your work.",
    level: "beginner",
    duration: "3 hours",
    students: 6200,
    rating: 4.8,
    tags: ["Social Media", "Marketing", "Career"],
    icon: "📱",
  },
];