// Comprehensive Creator Courses: Growth, Monetization, Strategy & Business
export const creatorCourses = [
  // === AUDIENCE GROWTH & DISCOVERY ===
  {
    id: 200,
    title: "Algorithm Mastery: YouTube Growth Hacking",
    description: "Understand YouTube's algorithm: keywords, CTR, watch time, and growth strategies.",
    level: "intermediate",
    duration: "4.5 hours",
    students: 8900,
    rating: 4.9,
    tags: ["YouTube", "Algorithm", "Growth"],
    icon: "📈",
  },
  {
    id: 201,
    title: "Viral Content Formulas",
    description: "Tested frameworks for creating viral content: hooks, patterns, and psychology.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 7200,
    rating: 4.8,
    tags: ["Content Strategy", "Viral", "Growth"],
    icon: "🔥",
  },
  {
    id: 202,
    title: "Thumbnail Psychology & Design",
    description: "Create thumbnails that get clicks: colors, text, faces, and A/B testing.",
    level: "beginner",
    duration: "2.5 hours",
    students: 6800,
    rating: 4.9,
    tags: ["Thumbnails", "Design", "CTR"],
    icon: "🖼️",
  },
  {
    id: 203,
    title: "Title Optimization for Maximum Views",
    description: "Craft compelling titles: keywords, curiosity gaps, and psychological triggers.",
    level: "beginner",
    duration: "2 hours",
    students: 7500,
    rating: 4.8,
    tags: ["Titles", "SEO", "CTR"],
    icon: "✍️",
  },
  {
    id: 204,
    title: "Shorts & TikTok Strategy",
    description: "Master short-form content: hooks, pacing, trends, and algorithm optimization.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 8200,
    rating: 4.8,
    tags: ["Shorts", "TikTok", "Short-form"],
    icon: "📱",
  },
  {
    id: 205,
    title: "Collaboration & Cross-Promotion",
    description: "Find collaborators, negotiate deals, and leverage cross-promotion for growth.",
    level: "intermediate",
    duration: "3 hours",
    students: 5100,
    rating: 4.8,
    tags: ["Collaboration", "Partnerships", "Growth"],
    icon: "🤝",
  },

  // === MONETIZATION & REVENUE ===
  {
    id: 206,
    title: "YouTube Monetization Mastery",
    description: "Maximize AdSense: CPM optimization, content strategy, and revenue growth.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 6900,
    rating: 4.8,
    tags: ["Monetization", "YouTube", "Revenue"],
    icon: "💰",
  },
  {
    id: 207,
    title: "Building Channel Memberships",
    description: "Launch membership programs: perks, pricing, and recurring revenue.",
    level: "intermediate",
    duration: "3 hours",
    students: 5200,
    rating: 4.8,
    tags: ["Memberships", "Recurring Revenue", "Monetization"],
    icon: "👑",
  },
  {
    id: 208,
    title: "Sponsorship Deal Strategy",
    description: "Land sponsorships: pitching, negotiating, and running sponsored content.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 4800,
    rating: 4.9,
    tags: ["Sponsorships", "Deals", "Revenue"],
    icon: "📋",
  },
  {
    id: 209,
    title: "Affiliate Marketing for Creators",
    description: "Earn commissions: product selection, promotion, and affiliate networks.",
    level: "beginner",
    duration: "3 hours",
    students: 5600,
    rating: 4.8,
    tags: ["Affiliate", "Monetization", "Revenue"],
    icon: "🔗",
  },
  {
    id: 210,
    title: "Digital Products & Course Creation",
    description: "Create and sell courses, ebooks, templates: production to marketing.",
    level: "intermediate",
    duration: "4.5 hours",
    students: 4700,
    rating: 4.8,
    tags: ["Digital Products", "Courses", "Revenue"],
    icon: "📚",
  },
  {
    id: 211,
    title: "Patreon & Fan Funding Strategies",
    description: "Build Patreon: tier design, rewards, and sustainable fan funding.",
    level: "beginner",
    duration: "2.5 hours",
    students: 4100,
    rating: 4.8,
    tags: ["Patreon", "Fan Funding", "Revenue"],
    icon: "❤️",
  },
  {
    id: 212,
    title: "Merchandise & Physical Products",
    description: "Launch merch: design, production, fulfillment, and marketing.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 3900,
    rating: 4.7,
    tags: ["Merchandise", "E-commerce", "Revenue"],
    icon: "👕",
  },

  // === CONTENT STRATEGY & PLANNING ===
  {
    id: 213,
    title: "Content Pillars & Long-term Strategy",
    description: "Build sustainable content: pillars, themes, and 12-month planning.",
    level: "intermediate",
    duration: "3 hours",
    students: 5900,
    rating: 4.8,
    tags: ["Strategy", "Planning", "Content"],
    icon: "📊",
  },
  {
    id: 214,
    title: "Consistency & Scheduling Mastery",
    description: "Build habits: optimal posting schedules, batching, and systems.",
    level: "beginner",
    duration: "2.5 hours",
    students: 6200,
    rating: 4.8,
    tags: ["Consistency", "Scheduling", "Productivity"],
    icon: "📅",
  },
  {
    id: 215,
    title: "Trending & Evergreen Content Mix",
    description: "Balance trending content with evergreen value for sustained growth.",
    level: "intermediate",
    duration: "2.5 hours",
    students: 4400,
    rating: 4.8,
    tags: ["Content Strategy", "Trends", "Growth"],
    icon: "🔄",
  },
  {
    id: 216,
    title: "Series & Episodic Content Planning",
    description: "Create binge-worthy series: arcs, cliffhangers, and retention.",
    level: "intermediate",
    duration: "3 hours",
    students: 4200,
    rating: 4.8,
    tags: ["Series", "Storytelling", "Retention"],
    icon: "📺",
  },
  {
    id: 217,
    title: "Reusing Content Across Platforms",
    description: "Repurpose one piece across YouTube, TikTok, Instagram, Twitter.",
    level: "beginner",
    duration: "2 hours",
    students: 5300,
    rating: 4.9,
    tags: ["Content Repurposing", "Multi-platform", "Efficiency"],
    icon: "♻️",
  },

  // === BRANDING & POSITIONING ===
  {
    id: 218,
    title: "Personal Brand Building for Creators",
    description: "Develop authentic brand: voice, values, positioning, and consistency.",
    level: "intermediate",
    duration: "4 hours",
    students: 6800,
    rating: 4.9,
    tags: ["Branding", "Personal Brand", "Positioning"],
    icon: "✨",
  },
  {
    id: 219,
    title: "Logo & Channel Art Design",
    description: "Create professional visual identity: logos, banners, and graphics.",
    level: "beginner",
    duration: "3 hours",
    students: 5100,
    rating: 4.8,
    tags: ["Design", "Branding", "Visual Identity"],
    icon: "🎨",
  },
  {
    id: 220,
    title: "Bio & Description Copywriting",
    description: "Write compelling bios: clarity, keywords, personality, and CTAs.",
    level: "beginner",
    duration: "1.5 hours",
    students: 5800,
    rating: 4.8,
    tags: ["Copywriting", "Branding", "Messaging"],
    icon: "📝",
  },
  {
    id: 221,
    title: "Niche Selection & Positioning",
    description: "Find your niche: underserved audiences and unique angles.",
    level: "beginner",
    duration: "2 hours",
    students: 6500,
    rating: 4.9,
    tags: ["Niche", "Positioning", "Strategy"],
    icon: "🎯",
  },

  // === COMMUNITY & ENGAGEMENT ===
  {
    id: 222,
    title: "Building Loyal Community",
    description: "Engage audience: Discord, comments, DMs, and fostering loyalty.",
    level: "intermediate",
    duration: "3 hours",
    students: 5600,
    rating: 4.8,
    tags: ["Community", "Engagement", "Loyalty"],
    icon: "👥",
  },
  {
    id: 223,
    title: "Comment Management & Response Strategies",
    description: "Build engagement: responding to comments, moderation, and retention.",
    level: "beginner",
    duration: "2 hours",
    students: 4900,
    rating: 4.8,
    tags: ["Engagement", "Comments", "Community"],
    icon: "💬",
  },
  {
    id: 224,
    title: "Discord Server Management",
    description: "Build thriving Discord: roles, channels, bots, and community culture.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 4200,
    rating: 4.8,
    tags: ["Discord", "Community", "Management"],
    icon: "🎮",
  },
  {
    id: 225,
    title: "Live Streaming Mastery",
    description: "Host engaging streams: setup, interaction, moderation, and growth.",
    level: "intermediate",
    duration: "4 hours",
    students: 5300,
    rating: 4.8,
    tags: ["Live Streaming", "Interaction", "Growth"],
    icon: "📡",
  },

  // === ANALYTICS & DATA ===
  {
    id: 226,
    title: "YouTube Analytics Deep Dive",
    description: "Understand metrics: watch time, retention, audience insights, CTR.",
    level: "intermediate",
    duration: "3 hours",
    students: 5800,
    rating: 4.8,
    tags: ["Analytics", "YouTube", "Data"],
    icon: "📊",
  },
  {
    id: 227,
    title: "Audience Demographics & Insights",
    description: "Know your audience: age, location, interests, and behavior patterns.",
    level: "beginner",
    duration: "2 hours",
    students: 4700,
    rating: 4.8,
    tags: ["Analytics", "Audience", "Data"],
    icon: "👤",
  },
  {
    id: 228,
    title: "A/B Testing for Optimization",
    description: "Scientific testing: thumbnails, titles, timing, and optimization.",
    level: "intermediate",
    duration: "2.5 hours",
    students: 4100,
    rating: 4.9,
    tags: ["A/B Testing", "Optimization", "Growth"],
    icon: "🧪",
  },
  {
    id: 229,
    title: "Tracking & Attribution",
    description: "Track revenue sources: affiliate links, discount codes, UTM parameters.",
    level: "intermediate",
    duration: "2 hours",
    students: 3200,
    rating: 4.8,
    tags: ["Tracking", "Attribution", "Analytics"],
    icon: "🔍",
  },

  // === TECHNICAL SETUP ===
  {
    id: 230,
    title: "Streaming Setup & Equipment",
    description: "Professional setup: camera, mic, lighting, encoder, and internet.",
    level: "beginner",
    duration: "3 hours",
    students: 6200,
    rating: 4.8,
    tags: ["Streaming", "Equipment", "Setup"],
    icon: "🎥",
  },
  {
    id: 231,
    title: "OBS Studio Masterclass",
    description: "Advanced OBS: scenes, overlays, transitions, and streaming setup.",
    level: "intermediate",
    duration: "4 hours",
    students: 5400,
    rating: 4.8,
    tags: ["OBS", "Streaming", "Software"],
    icon: "⚙️",
  },
  {
    id: 232,
    title: "Audio Production for Creators",
    description: "Professional audio: mic choice, editing, sound design, and mastering.",
    level: "intermediate",
    duration: "4.5 hours",
    students: 4800,
    rating: 4.8,
    tags: ["Audio", "Production", "Quality"],
    icon: "🎙️",
  },
  {
    id: 233,
    title: "Video Editing Workflow Optimization",
    description: "Efficient editing: templates, shortcuts, color grading, and exports.",
    level: "intermediate",
    duration: "5 hours",
    students: 5600,
    rating: 4.8,
    tags: ["Video Editing", "Workflow", "Efficiency"],
    icon: "✂️",
  },
  {
    id: 234,
    title: "Green Screen & Lighting Setup",
    description: "Professional lighting: 3-point, ring lights, green screen techniques.",
    level: "beginner",
    duration: "2.5 hours",
    students: 4200,
    rating: 4.8,
    tags: ["Lighting", "Setup", "Quality"],
    icon: "💡",
  },

  // === SEO & DISCOVERY ===
  {
    id: 235,
    title: "YouTube SEO Fundamentals",
    description: "Search optimization: keywords, tags, descriptions, and discovery.",
    level: "intermediate",
    duration: "3 hours",
    students: 6100,
    rating: 4.9,
    tags: ["SEO", "YouTube", "Discovery"],
    icon: "🔎",
  },
  {
    id: 236,
    title: "Keyword Research for Creators",
    description: "Find high-value keywords: volume, competition, and search intent.",
    level: "intermediate",
    duration: "2.5 hours",
    students: 5300,
    rating: 4.8,
    tags: ["Keywords", "SEO", "Research"],
    icon: "📚",
  },
  {
    id: 237,
    title: "Playlists & Playlist Strategy",
    description: "Maximize playlists: creation, organization, and suggested video flow.",
    level: "beginner",
    duration: "2 hours",
    students: 4600,
    rating: 4.8,
    tags: ["Playlists", "Organization", "Watch Time"],
    icon: "📝",
  },
  {
    id: 238,
    title: "Cards & End Screens Mastery",
    description: "Optimize retention: strategic cards, end screens, and subscriptions.",
    level: "beginner",
    duration: "1.5 hours",
    students: 4100,
    rating: 4.8,
    tags: ["Cards", "End Screens", "CTR"],
    icon: "🎯",
  },

  // === COPYWRITING & MESSAGING ===
  {
    id: 239,
    title: "Persuasive Copywriting for Creators",
    description: "Write compelling copy: hooks, benefits, emotional appeal, and CTAs.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 5200,
    rating: 4.9,
    tags: ["Copywriting", "Persuasion", "Messaging"],
    icon: "✍️",
  },
  {
    id: 240,
    title: "Email Marketing for Creators",
    description: "Build email list: segmentation, automation, and monetization.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 4500,
    rating: 4.8,
    tags: ["Email", "Marketing", "Automation"],
    icon: "📧",
  },
  {
    id: 241,
    title: "Social Media Captions That Convert",
    description: "Write captions: hooks, formatting, hashtags, and engagement.",
    level: "beginner",
    duration: "2 hours",
    students: 5900,
    rating: 4.8,
    tags: ["Social Media", "Captions", "Copywriting"],
    icon: "📱",
  },
  {
    id: 242,
    title: "Storytelling Framework for Content",
    description: "Master storytelling: narrative structure, hooks, and emotional arcs.",
    level: "intermediate",
    duration: "3 hours",
    students: 5100,
    rating: 4.9,
    tags: ["Storytelling", "Content", "Engagement"],
    icon: "📖",
  },

  // === BUSINESS & LEGAL ===
  {
    id: 243,
    title: "Creator Business Setup",
    description: "Business fundamentals: LLC vs Sole Prop, taxes, and accounting.",
    level: "beginner",
    duration: "3 hours",
    students: 4800,
    rating: 4.8,
    tags: ["Business", "Legal", "Setup"],
    icon: "⚖️",
  },
  {
    id: 244,
    title: "Copyright & Fair Use for Creators",
    description: "Protect yourself: fair use, copyright claims, takedowns, and licensing.",
    level: "beginner",
    duration: "2.5 hours",
    students: 4200,
    rating: 4.8,
    tags: ["Copyright", "Legal", "Protection"],
    icon: "🛡️",
  },
  {
    id: 245,
    title: "Contract Negotiation for Deals",
    description: "Negotiate confidently: sponsorships, licensing, and partnership deals.",
    level: "intermediate",
    duration: "3 hours",
    students: 3600,
    rating: 4.9,
    tags: ["Contracts", "Negotiation", "Deals"],
    icon: "📋",
  },
  {
    id: 246,
    title: "Tax Planning for Creators",
    description: "Optimize taxes: deductions, quarterly payments, and IRS compliance.",
    level: "intermediate",
    duration: "2.5 hours",
    students: 3200,
    rating: 4.8,
    tags: ["Taxes", "Finance", "Business"],
    icon: "💵",
  },
  {
    id: 247,
    title: "Financial Management for Creators",
    description: "Manage income: accounting, budgeting, savings, and investing.",
    level: "intermediate",
    duration: "3 hours",
    students: 3800,
    rating: 4.8,
    tags: ["Finance", "Business", "Planning"],
    icon: "💰",
  },

  // === PSYCHOLOGY & PERSUASION ===
  {
    id: 248,
    title: "Psychological Triggers in Content",
    description: "Use psychology: curiosity, scarcity, social proof, and urgency.",
    level: "intermediate",
    duration: "3 hours",
    students: 5400,
    rating: 4.9,
    tags: ["Psychology", "Persuasion", "Growth"],
    icon: "🧠",
  },
  {
    id: 249,
    title: "Habit Formation & Viewer Behavior",
    description: "Create habits: notification patterns, content timing, and loyalty.",
    level: "intermediate",
    duration: "2.5 hours",
    students: 4100,
    rating: 4.8,
    tags: ["Psychology", "Habit", "Viewer Behavior"],
    icon: "🎯",
  },
  {
    id: 250,
    title: "Audience Retention Techniques",
    description: "Hook viewers: pacing, cuts, cliffhangers, and retention mechanics.",
    level: "intermediate",
    duration: "3 hours",
    students: 5800,
    rating: 4.8,
    tags: ["Retention", "Pacing", "Psychology"],
    icon: "🎬",
  },

  // === SPECIAL TOPICS ===
  {
    id: 251,
    title: "Podcast Growth & Monetization",
    description: "Build podcast audience: distribution, sponsorships, and Spotify growth.",
    level: "intermediate",
    duration: "3.5 hours",
    students: 3900,
    rating: 4.8,
    tags: ["Podcast", "Audio", "Monetization"],
    icon: "🎙️",
  },
  {
    id: 252,
    title: "Twitch Streaming Mastery",
    description: "Grow on Twitch: affiliate, raids, categories, and community.",
    level: "intermediate",
    duration: "4 hours",
    students: 4600,
    rating: 4.8,
    tags: ["Twitch", "Streaming", "Gaming"],
    icon: "🎮",
  },
  {
    id: 253,
    title: "TikTok Algorithm & Creator Fund",
    description: "Master TikTok: algorithm, trends, creator fund, and growth hacks.",
    level: "intermediate",
    duration: "3 hours",
    students: 6500,
    rating: 4.8,
    tags: ["TikTok", "Algorithm", "Short-form"],
    icon: "📱",
  },
  {
    id: 254,
    title: "Instagram & Reels Strategy",
    description: "Grow Instagram: reels algorithm, stories, DMs, and engagement.",
    level: "intermediate",
    duration: "3 hours",
    students: 5200,
    rating: 4.8,
    tags: ["Instagram", "Reels", "Growth"],
    icon: "📸",
  },
  {
    id: 255,
    title: "Twitter & Community Building",
    description: "Leverage Twitter: threading, engagement, audience building.",
    level: "beginner",
    duration: "2.5 hours",
    students: 4300,
    rating: 4.8,
    tags: ["Twitter", "Social Media", "Community"],
    icon: "🐦",
  },

  // === ADVANCED TOPICS ===
  {
    id: 256,
    title: "Scaling Your Creator Business",
    description: "Grow sustainably: hiring, outsourcing, systems, and scaling.",
    level: "advanced",
    duration: "4 hours",
    students: 2800,
    rating: 4.9,
    tags: ["Scaling", "Business", "Advanced"],
    icon: "📈",
  },
  {
    id: 257,
    title: "Personal Brand PR & Media",
    description: "Get featured: PR strategy, press releases, and media outreach.",
    level: "advanced",
    duration: "3.5 hours",
    students: 2400,
    rating: 4.8,
    tags: ["PR", "Media", "Branding"],
    icon: "📢",
  },
  {
    id: 258,
    title: "Influencer Partnerships & Deals",
    description: "Land big deals: pitching, rates, contracts, and partnership strategy.",
    level: "advanced",
    duration: "3.5 hours",
    students: 2600,
    rating: 4.9,
    tags: ["Partnerships", "Deals", "Advanced"],
    icon: "🤝",
  },
  {
    id: 259,
    title: "Crisis Management for Creators",
    description: "Navigate controversies: response strategy, damage control, recovery.",
    level: "advanced",
    duration: "2.5 hours",
    students: 2100,
    rating: 4.8,
    tags: ["Crisis Management", "Public Relations", "Advanced"],
    icon: "🚨",
  },
  {
    id: 260,
    title: "Monetization Diversification",
    description: "Multiple revenue streams: balancing AdSense, sponsors, and products.",
    level: "advanced",
    duration: "3 hours",
    students: 2900,
    rating: 4.9,
    tags: ["Monetization", "Revenue", "Advanced"],
    icon: "💼",
  },
];