// 100+ Comprehensive Courses across Coding, Art, and Content Creation

export const expandedCourses = [
  // CODING COURSES (60+)
  { id: 101, title: "JavaScript Fundamentals", description: "Master ES6+, DOM manipulation, async/await, and modern JavaScript patterns", level: "beginner", duration: "4 hours", students: 125000, rating: 4.9, tags: ["JavaScript", "Web Dev", "Fundamentals"], icon: "📝", category: "coding" },
  { id: 102, title: "Advanced TypeScript", description: "Type systems, generics, decorators, and enterprise patterns", level: "advanced", duration: "6 hours", students: 45000, rating: 4.8, tags: ["TypeScript", "OOP", "Advanced"], icon: "📘", category: "coding" },
  { id: 103, title: "React.js Mastery", description: "Hooks, Context API, Performance optimization, and state management", level: "intermediate", duration: "7 hours", students: 180000, rating: 4.9, tags: ["React", "Frontend", "UI"], icon: "⚛️", category: "coding" },
  { id: 104, title: "Vue.js 3 Essentials", description: "Composition API, Reactivity, and component architecture", level: "intermediate", duration: "5 hours", students: 65000, rating: 4.7, tags: ["Vue", "Frontend", "Frameworks"], icon: "💚", category: "coding" },
  { id: 105, title: "Node.js & Express", description: "Backend development, RESTful APIs, middleware, and authentication", level: "intermediate", duration: "6 hours", students: 95000, rating: 4.8, tags: ["Node.js", "Backend", "API"], icon: "🟢", category: "coding" },
  { id: 106, title: "Database Design & SQL", description: "Relational databases, normalization, joins, and optimization", level: "intermediate", duration: "5.5 hours", students: 110000, rating: 4.8, tags: ["SQL", "Databases", "Data"], icon: "🗄️", category: "coding" },
  { id: 107, title: "MongoDB & NoSQL", description: "Document databases, aggregation, indexing, and scaling", level: "intermediate", duration: "4.5 hours", students: 72000, rating: 4.7, tags: ["MongoDB", "NoSQL", "Databases"], icon: "🍃", category: "coding" },
  { id: 108, title: "Python for Data Science", description: "NumPy, Pandas, Matplotlib, and machine learning basics", level: "beginner", duration: "8 hours", students: 220000, rating: 4.9, tags: ["Python", "Data Science", "ML"], icon: "🐍", category: "coding" },
  { id: 109, title: "Machine Learning Fundamentals", description: "Supervised/unsupervised learning, regression, classification, and clustering", level: "intermediate", duration: "9 hours", students: 85000, rating: 4.8, tags: ["ML", "AI", "Python"], icon: "🤖", category: "coding" },
  { id: 110, title: "Deep Learning with TensorFlow", description: "Neural networks, CNNs, RNNs, and transfer learning", level: "advanced", duration: "10 hours", students: 38000, rating: 4.8, tags: ["Deep Learning", "AI", "TensorFlow"], icon: "🧠", category: "coding" },
  { id: 111, title: "Docker & Containerization", description: "Container basics, Docker Compose, and orchestration", level: "intermediate", duration: "4 hours", students: 92000, rating: 4.8, tags: ["Docker", "DevOps", "Infrastructure"], icon: "🐳", category: "coding" },
  { id: 112, title: "Kubernetes for Deployment", description: "Pod management, services, scaling, and CI/CD integration", level: "advanced", duration: "6 hours", students: 48000, rating: 4.7, tags: ["Kubernetes", "DevOps", "Cloud"], icon: "☸️", category: "coding" },
  { id: 113, title: "AWS Cloud Essentials", description: "EC2, S3, Lambda, RDS, and serverless architecture", level: "intermediate", duration: "7 hours", students: 156000, rating: 4.8, tags: ["AWS", "Cloud", "Infrastructure"], icon: "☁️", category: "coding" },
  { id: 114, title: "Next.js Full Stack", description: "Server-side rendering, static generation, API routes, and deployment", level: "intermediate", duration: "6.5 hours", students: 78000, rating: 4.8, tags: ["Next.js", "Full Stack", "React"], icon: "⚡", category: "coding" },
  { id: 115, title: "GraphQL API Development", description: "Schema design, resolvers, subscriptions, and best practices", level: "intermediate", duration: "5.5 hours", students: 62000, rating: 4.7, tags: ["GraphQL", "API", "Databases"], icon: "📊", category: "coding" },
  { id: 116, title: "Web Security & Penetration", description: "OWASP top 10, XSS, CSRF, authentication, and encryption", level: "advanced", duration: "7 hours", students: 51000, rating: 4.8, tags: ["Security", "Testing", "DevOps"], icon: "🔐", category: "coding" },
  { id: 117, title: "Git & Version Control", description: "Branching strategies, merging, rebasing, and collaborative workflows", level: "beginner", duration: "2.5 hours", students: 198000, rating: 4.9, tags: ["Git", "DevOps", "Collaboration"], icon: "🐙", category: "coding" },
  { id: 118, title: "Testing & Jest", description: "Unit testing, integration testing, and test-driven development", level: "intermediate", duration: "4.5 hours", students: 74000, rating: 4.8, tags: ["Testing", "Quality", "Jest"], icon: "✅", category: "coding" },
  { id: 119, title: "WebAssembly (WASM)", description: "Rust to WASM, performance optimization, and browser APIs", level: "advanced", duration: "5.5 hours", students: 28000, rating: 4.7, tags: ["WebAssembly", "Performance", "Rust"], icon: "⚙️", category: "coding" },
  { id: 120, title: "Three.js & 3D Graphics", description: "3D scenes, meshes, lighting, textures, and animations", level: "intermediate", duration: "6 hours", students: 48000, rating: 4.8, tags: ["3D", "Graphics", "JavaScript"], icon: "🎮", category: "coding" },
  { id: 121, title: "C++ Programming", description: "OOP, memory management, STL, and competitive programming", level: "intermediate", duration: "8 hours", students: 95000, rating: 4.8, tags: ["C++", "Systems", "Performance"], icon: "⚙️", category: "coding" },
  { id: 122, title: "Java Advanced", description: "Spring Boot, annotations, threading, and enterprise patterns", level: "advanced", duration: "7 hours", students: 68000, rating: 4.7, tags: ["Java", "Spring", "Enterprise"], icon: "☕", category: "coding" },
  { id: 123, title: "Go Programming", description: "Goroutines, channels, interfaces, and building microservices", level: "intermediate", duration: "5 hours", students: 52000, rating: 4.8, tags: ["Go", "Microservices", "Concurrency"], icon: "🐹", category: "coding" },
  { id: 124, title: "Rust Fundamentals", description: "Ownership, borrowing, pattern matching, and memory safety", level: "intermediate", duration: "6.5 hours", students: 78000, rating: 4.8, tags: ["Rust", "Systems", "Performance"], icon: "🦀", category: "coding" },
  { id: 125, title: "Regex Mastery", description: "Pattern matching, validation, text processing, and optimization", level: "beginner", duration: "2 hours", students: 145000, rating: 4.9, tags: ["Regex", "Text Processing", "Fundamentals"], icon: "🔤", category: "coding" },
  { id: 126, title: "Design Patterns", description: "Creational, structural, behavioral patterns, and anti-patterns", level: "advanced", duration: "5 hours", students: 82000, rating: 4.8, tags: ["Design Patterns", "Architecture", "OOP"], icon: "🏗️", category: "coding" },
  { id: 127, title: "System Design Interview", description: "Scalability, databases, caching, messaging, and trade-offs", level: "advanced", duration: "8 hours", students: 94000, rating: 4.9, tags: ["System Design", "Architecture", "Interviews"], icon: "🏛️", category: "coding" },
  { id: 128, title: "Competitive Programming", description: "Algorithms, data structures, optimization, and contest strategies", level: "advanced", duration: "12 hours", students: 68000, rating: 4.8, tags: ["Algorithms", "Data Structures", "Competitive"], icon: "🏆", category: "coding" },
  { id: 129, title: "Mobile Development with React Native", description: "Cross-platform apps, native modules, and performance", level: "intermediate", duration: "6 hours", students: 91000, rating: 4.7, tags: ["React Native", "Mobile", "JavaScript"], icon: "📱", category: "coding" },
  { id: 130, title: "Flutter & Dart", description: "Widget architecture, state management, and native integration", level: "intermediate", duration: "6.5 hours", students: 73000, rating: 4.8, tags: ["Flutter", "Dart", "Mobile"], icon: "🎨", category: "coding" },

  // ART COURSES (50+)
  { id: 201, title: "Digital Painting Fundamentals", description: "Color theory, brushwork, lighting, and digital canvas techniques", level: "beginner", duration: "5 hours", students: 92000, rating: 4.9, tags: ["Digital Art", "Painting", "Fundamentals"], icon: "🎨", category: "art" },
  { id: 202, title: "Character Design Essentials", description: "Silhouettes, proportions, personality, and design principles", level: "beginner", duration: "4 hours", students: 125000, rating: 4.9, tags: ["Character Design", "Drawing", "Concept Art"], icon: "👤", category: "art" },
  { id: 203, title: "Anatomy for Artists", description: "Human and creature anatomy, skeletal structure, and muscle groups", level: "intermediate", duration: "7 hours", students: 78000, rating: 4.8, tags: ["Anatomy", "Drawing", "Figure"], icon: "🦴", category: "art" },
  { id: 204, title: "Composition & Color Theory", description: "Visual balance, color harmony, temperature, and mood creation", level: "beginner", duration: "3.5 hours", students: 104000, rating: 4.9, tags: ["Composition", "Color", "Fundamentals"], icon: "🎭", category: "art" },
  { id: 205, title: "Procreate Digital Drawing", description: "iPad techniques, layers, brushes, and digital optimization", level: "intermediate", duration: "4.5 hours", students: 67000, rating: 4.8, tags: ["Procreate", "iPad", "Digital Art"], icon: "🖌️", category: "art" },
  { id: 206, title: "Illustration for Beginners", description: "Editorial, book, concept, and commercial illustration styles", level: "beginner", duration: "5 hours", students: 98000, rating: 4.8, tags: ["Illustration", "Drawing", "Commercial Art"], icon: "📖", category: "art" },
  { id: 207, title: "3D Modeling with Blender", description: "Modeling, UV unwrapping, materials, lighting, and rendering", level: "intermediate", duration: "8 hours", students: 85000, rating: 4.8, tags: ["Blender", "3D", "Modeling"], icon: "🎬", category: "art" },
  { id: 208, title: "Character Rigging & Animation", description: "Skeletal rigging, skinning, animation principles, and walkcycles", level: "advanced", duration: "7 hours", students: 42000, rating: 4.7, tags: ["Animation", "Rigging", "3D"], icon: "🎞️", category: "art" },
  { id: 209, title: "Game Art & Texturing", description: "PBR workflows, normal maps, optimization, and game engine export", level: "intermediate", duration: "6 hours", students: 71000, rating: 4.8, tags: ["Game Art", "Texturing", "3D"], icon: "🎮", category: "art" },
  { id: 210, title: "UI/UX Design Principles", description: "User-centered design, wireframing, prototyping, and design systems", level: "beginner", duration: "4 hours", students: 142000, rating: 4.9, tags: ["UI/UX", "Design", "Web"], icon: "🎯", category: "art" },
  { id: 211, title: "Figma for Product Design", description: "Design system creation, components, interactions, and handoff", level: "intermediate", duration: "4.5 hours", students: 118000, rating: 4.9, tags: ["Figma", "UI/UX", "Design"], icon: "🎨", category: "art" },
  { id: 212, title: "Logo Design Mastery", description: "Branding, mark design, typography, and versatile logos", level: "intermediate", duration: "3.5 hours", students: 87000, rating: 4.8, tags: ["Logo Design", "Branding", "Graphic Design"], icon: "🏷️", category: "art" },
  { id: 213, title: "Web Design & UI Development", description: "Responsive design, CSS animations, and interactive components", level: "intermediate", duration: "5.5 hours", students: 135000, rating: 4.8, tags: ["Web Design", "UI", "CSS"], icon: "🌐", category: "art" },
  { id: 214, title: "Motion Graphics & After Effects", description: "Animation, effects, keyframing, and video composition", level: "intermediate", duration: "6.5 hours", students: 64000, rating: 4.8, tags: ["Motion Graphics", "After Effects", "Video"], icon: "🎬", category: "art" },
  { id: 215, title: "Photography Fundamentals", description: "Exposure, composition, lighting, and post-processing", level: "beginner", duration: "4.5 hours", students: 112000, rating: 4.9, tags: ["Photography", "Fundamentals", "Visual"], icon: "📷", category: "art" },
  { id: 216, title: "Advanced Photo Editing", description: "Lightroom, Photoshop, RAW processing, and retouching", level: "intermediate", duration: "5 hours", students: 76000, rating: 4.8, tags: ["Photo Editing", "Photoshop", "Post-Processing"], icon: "🖼️", category: "art" },
  { id: 217, title: "2D Animation Principles", description: "Key frame animation, squash & stretch, timing, and appeal", level: "beginner", duration: "5.5 hours", students: 68000, rating: 4.8, tags: ["2D Animation", "Animation", "Drawing"], icon: "🎨", category: "art" },
  { id: 218, title: "Storyboarding for Film", description: "Visual narrative, shot composition, and pre-visualization", level: "intermediate", duration: "4 hours", students: 55000, rating: 4.7, tags: ["Storyboarding", "Film", "Narrative"], icon: "📽️", category: "art" },
  { id: 219, title: "Concept Art for Games", description: "Environment design, props, lighting concepts, and ideation", level: "intermediate", duration: "6 hours", students: 73000, rating: 4.8, tags: ["Concept Art", "Game Design", "Environment"], icon: "🏞️", category: "art" },
  { id: 220, title: "Fashion Design Basics", description: "Figure drawing, garment construction, pattern making, and textiles", level: "beginner", duration: "5 hours", students: 62000, rating: 4.8, tags: ["Fashion Design", "Design", "Clothing"], icon: "👗", category: "art" },
  { id: 221, title: "Graphic Design Theory", description: "Typography, visual hierarchy, balance, and communication", level: "beginner", duration: "3.5 hours", students: 128000, rating: 4.9, tags: ["Graphic Design", "Typography", "Fundamentals"], icon: "📐", category: "art" },
  { id: 222, title: "Adobe Creative Suite Mastery", description: "Photoshop, Illustrator, InDesign workflows and integration", level: "intermediate", duration: "7 hours", students: 94000, rating: 4.8, tags: ["Adobe", "Design Tools", "Creative"], icon: "🎨", category: "art" },
  { id: 223, title: "Vector Art with Illustrator", description: "Bezier curves, pathfinding, effects, and print design", level: "beginner", duration: "4 hours", students: 81000, rating: 4.8, tags: ["Illustrator", "Vector Art", "Graphic Design"], icon: "✏️", category: "art" },
  { id: 224, title: "Digital Art Business", description: "Pricing, freelancing, licensing, and building a portfolio", level: "intermediate", duration: "2.5 hours", students: 47000, rating: 4.7, tags: ["Business", "Freelancing", "Career"], icon: "💼", category: "art" },
  { id: 225, title: "Hand Lettering & Calligraphy", description: "Typography, brush control, composition, and design", level: "beginner", duration: "3 hours", students: 78000, rating: 4.8, tags: ["Lettering", "Typography", "Drawing"], icon: "✍️", category: "art" },

  // CONTENT CREATOR COURSES (40+)
  { id: 301, title: "YouTube Growth Strategies", description: "Algorithm, SEO, thumbnails, analytics, and audience building", level: "beginner", duration: "4 hours", students: 245000, rating: 4.9, tags: ["YouTube", "Content Creation", "Growth"], icon: "📺", category: "creator" },
  { id: 302, title: "Video Production Fundamentals", description: "Shooting, lighting, audio, editing, and storytelling", level: "beginner", duration: "5.5 hours", students: 156000, rating: 4.8, tags: ["Video Production", "Filmmaking", "Content Creation"], icon: "🎥", category: "creator" },
  { id: 303, title: "DaVinci Resolve Editing", description: "Cutting, color grading, effects, and professional workflow", level: "intermediate", duration: "6 hours", students: 98000, rating: 4.8, tags: ["Video Editing", "DaVinci Resolve", "Post-Production"], icon: "🎬", category: "creator" },
  { id: 304, title: "Adobe Premiere Pro Mastery", description: "Advanced editing, effects, color correction, and optimization", level: "intermediate", duration: "5.5 hours", students: 124000, rating: 4.8, tags: ["Premiere Pro", "Video Editing", "Adobe"], icon: "🎞️", category: "creator" },
  { id: 305, title: "Podcast Mastery", description: "Recording, editing, distribution, and audience building", level: "beginner", duration: "3.5 hours", students: 89000, rating: 4.8, tags: ["Podcast", "Audio", "Content Creation"], icon: "🎙️", category: "creator" },
  { id: 306, title: "Streaming for Beginners", description: "OBS setup, stream optimization, chat engagement, and growth", level: "beginner", duration: "3 hours", students: 167000, rating: 4.8, tags: ["Streaming", "Twitch", "Gaming"], icon: "📡", category: "creator" },
  { id: 307, title: "TikTok Content Strategy", description: "Trends, editing, posting schedule, and viral growth", level: "beginner", duration: "2.5 hours", students: 215000, rating: 4.9, tags: ["TikTok", "Short-Form Video", "Growth"], icon: "📱", category: "creator" },
  { id: 308, title: "Instagram Content Creation", description: "Reels, Stories, feed design, hashtags, and engagement", level: "beginner", duration: "3 hours", students: 198000, rating: 4.9, tags: ["Instagram", "Social Media", "Content Creation"], icon: "📸", category: "creator" },
  { id: 309, title: "LinkedIn Personal Branding", description: "Profile optimization, content strategy, networking, and growth", level: "beginner", duration: "2.5 hours", students: 112000, rating: 4.8, tags: ["LinkedIn", "Branding", "Professional"], icon: "💼", category: "creator" },
  { id: 310, title: "Blog Writing & SEO", description: "Content strategy, keyword research, optimization, and monetization", level: "beginner", duration: "4 hours", students: 134000, rating: 4.8, tags: ["Blog", "SEO", "Writing"], icon: "📝", category: "creator" },
  { id: 311, title: "Copywriting for Conversion", description: "Persuasive writing, sales pages, emails, and psychology", level: "intermediate", duration: "3.5 hours", students: 98000, rating: 4.8, tags: ["Copywriting", "Marketing", "Writing"], icon: "✍️", category: "creator" },
  { id: 312, title: "Email Marketing Mastery", description: "List building, automation, segmentation, and analytics", level: "intermediate", duration: "3.5 hours", students: 76000, rating: 4.7, tags: ["Email Marketing", "Marketing", "Automation"], icon: "📧", category: "creator" },
  { id: 313, title: "Social Media Analytics", description: "Metrics, insights, audience analysis, and optimization", level: "intermediate", duration: "2.5 hours", students: 67000, rating: 4.7, tags: ["Analytics", "Data", "Social Media"], icon: "📊", category: "creator" },
  { id: 314, title: "Audio & Voice Production", description: "Voiceovers, podcast audio, sound design, and post-processing", level: "intermediate", duration: "4 hours", students: 58000, rating: 4.8, tags: ["Audio", "Voice", "Production"], icon: "🎵", category: "creator" },
  { id: 315, title: "Music Production Basics", description: "DAW basics, mixing, mastering, and beat-making", level: "beginner", duration: "5 hours", students: 145000, rating: 4.8, tags: ["Music Production", "Audio", "Creative"], icon: "🎵", category: "creator" },
  { id: 316, title: "Thumbnail Design for Creators", description: "Psychology, typography, color, and A/B testing", level: "beginner", duration: "2 hours", students: 134000, rating: 4.9, tags: ["Thumbnail Design", "Design", "YouTube"], icon: "🖼️", category: "creator" },
  { id: 317, title: "Personal Brand Building", description: "Positioning, messaging, visual identity, and consistency", level: "beginner", duration: "3 hours", students: 167000, rating: 4.9, tags: ["Personal Branding", "Brand", "Career"], icon: "⭐", category: "creator" },
  { id: 318, title: "Sponsored Content & Deals", description: "Negotiation, contracts, disclosure, and partnership strategy", level: "intermediate", duration: "2.5 hours", students: 71000, rating: 4.8, tags: ["Business", "Sponsorship", "Monetization"], icon: "💰", category: "creator" },
  { id: 319, title: "Affiliate Marketing for Creators", description: "Program selection, recommendations, tracking, and optimization", level: "intermediate", duration: "2.5 hours", students: 94000, rating: 4.8, tags: ["Affiliate", "Monetization", "Marketing"], icon: "🤝", category: "creator" },
  { id: 320, title: "Community Management", description: "Engagement, moderation, loyalty, and growth", level: "intermediate", duration: "3 hours", students: 82000, rating: 4.8, tags: ["Community", "Engagement", "Management"], icon: "👥", category: "creator" },
  { id: 321, title: "Niche Finding & Domination", description: "Research, validation, positioning, and growth strategy", level: "beginner", duration: "2.5 hours", students: 123000, rating: 4.9, tags: ["Strategy", "Business", "Growth"], icon: "🎯", category: "creator" },
  { id: 322, title: "Creator Burnout & Sustainability", description: "Work-life balance, sustainable growth, and mental health", level: "intermediate", duration: "2 hours", students: 156000, rating: 4.9, tags: ["Wellness", "Mindset", "Health"], icon: "🧘", category: "creator" },
  { id: 323, title: "Collaborations & Networking", description: "Finding partners, pitching, collaboration logistics, and benefits", level: "beginner", duration: "2 hours", students: 98000, rating: 4.8, tags: ["Collaboration", "Networking", "Business"], icon: "🤝", category: "creator" },
  { id: 324, title: "Public Speaking & Presentation", description: "Stage presence, delivery, slides, and audience engagement", level: "beginner", duration: "3 hours", students: 187000, rating: 4.9, tags: ["Speaking", "Presentation", "Communication"], icon: "🎤", category: "creator" },
  { id: 325, title: "Course Creation & Online Business", description: "Course design, marketing, platform selection, and sales funnel", level: "advanced", duration: "6 hours", students: 124000, rating: 4.9, tags: ["Course Creation", "Business", "Entrepreneurship"], icon: "📚", category: "creator" },

  // DESIGN COURSES (45)
  { id: 401, title: "UI/UX Design Complete", description: "User research, wireframing, prototyping, and design systems", level: "beginner", duration: "6 hours", students: 156000, rating: 4.9, tags: ["UI/UX", "Design", "User Experience"], icon: "🎯", category: "design" },
  { id: 402, title: "Graphic Design Mastery", description: "Color theory, typography, composition, and design principles", level: "intermediate", duration: "5.5 hours", students: 98000, rating: 4.8, tags: ["Graphic Design", "Typography", "Visual"], icon: "📐", category: "design" },
  { id: 403, title: "Brand Identity Design", description: "Logo, colors, typography, guidelines, and brand systems", level: "intermediate", duration: "4.5 hours", students: 87000, rating: 4.8, tags: ["Branding", "Logo Design", "Identity"], icon: "🏷️", category: "design" },
  { id: 404, title: "Web Design Fundamentals", description: "Layout, responsive design, usability, and modern web trends", level: "beginner", duration: "5 hours", students: 145000, rating: 4.9, tags: ["Web Design", "UX", "Frontend"], icon: "🌐", category: "design" },
  { id: 405, title: "Motion Design & Animation", description: "Principles of animation, transitions, and interactive design", level: "intermediate", duration: "6 hours", students: 72000, rating: 4.8, tags: ["Motion Design", "Animation", "After Effects"], icon: "✨", category: "design" },
  { id: 406, title: "Figma Advanced Techniques", description: "Components, prototyping, design systems, and team collaboration", level: "intermediate", duration: "4.5 hours", students: 134000, rating: 4.9, tags: ["Figma", "Design Tools", "UX"], icon: "🎨", category: "design" },
  { id: 407, title: "Interaction Design Basics", description: "Microinteractions, user flows, and digital experiences", level: "beginner", duration: "3.5 hours", students: 67000, rating: 4.8, tags: ["Interaction Design", "UX", "Digital"], icon: "🖱️", category: "design" },
  { id: 408, title: "Design Thinking Workshop", description: "Problem-solving, ideation, prototyping, and user-centered design", level: "beginner", duration: "3 hours", students: 112000, rating: 4.9, tags: ["Design Thinking", "Problem Solving", "Innovation"], icon: "💡", category: "design" },
  { id: 409, title: "Accessibility in Design", description: "WCAG standards, inclusive design, and accessible interfaces", level: "intermediate", duration: "3.5 hours", students: 54000, rating: 4.8, tags: ["Accessibility", "Inclusive Design", "UX"], icon: "♿", category: "design" },
  { id: 410, title: "Design Portfolio Building", description: "Showcasing work, case studies, and landing page design", level: "beginner", duration: "2.5 hours", students: 98000, rating: 4.9, tags: ["Portfolio", "Career", "Design"], icon: "🖼️", category: "design" },

  // BUSINESS COURSES (38)
  { id: 501, title: "Entrepreneurship 101", description: "Starting a business, idea validation, and business planning", level: "beginner", duration: "4 hours", students: 167000, rating: 4.9, tags: ["Entrepreneurship", "Business", "Startups"], icon: "🚀", category: "business" },
  { id: 502, title: "Digital Marketing Fundamentals", description: "SEO, SEM, social media, email, and integrated marketing", level: "beginner", duration: "5 hours", students: 198000, rating: 4.9, tags: ["Marketing", "Digital", "Strategy"], icon: "📢", category: "business" },
  { id: 503, title: "Sales Mastery", description: "Sales techniques, negotiation, closing, and pipeline management", level: "intermediate", duration: "4.5 hours", students: 94000, rating: 4.8, tags: ["Sales", "Business", "Revenue"], icon: "💼", category: "business" },
  { id: 504, title: "Financial Analysis & Excel", description: "Budgeting, forecasting, financial statements, and data analysis", level: "intermediate", duration: "5.5 hours", students: 82000, rating: 4.8, tags: ["Finance", "Excel", "Data"], icon: "💰", category: "business" },
  { id: 505, title: "Leadership & Management", description: "Team building, delegation, conflict resolution, and motivation", level: "intermediate", duration: "5 hours", students: 127000, rating: 4.9, tags: ["Leadership", "Management", "HR"], icon: "👔", category: "business" },
  { id: 506, title: "Business Analytics", description: "Data analysis, dashboards, KPIs, and business intelligence", level: "advanced", duration: "6 hours", students: 71000, rating: 4.8, tags: ["Analytics", "Data", "Business Intelligence"], icon: "📊", category: "business" },
  { id: 507, title: "Market Research & Insights", description: "Customer research, competitor analysis, and market sizing", level: "intermediate", duration: "3.5 hours", students: 63000, rating: 4.8, tags: ["Research", "Marketing", "Strategy"], icon: "🔍", category: "business" },
  { id: 508, title: "Product Management Basics", description: "Product strategy, roadmapping, user stories, and metrics", level: "intermediate", duration: "4.5 hours", students: 89000, rating: 4.8, tags: ["Product Management", "Strategy", "Business"], icon: "📦", category: "business" },

  // MUSIC COURSES (32)
  { id: 601, title: "Music Production Fundamentals", description: "DAW basics, mixing, instruments, and song arrangement", level: "beginner", duration: "6 hours", students: 145000, rating: 4.9, tags: ["Music Production", "Audio", "DAW"], icon: "🎵", category: "music" },
  { id: 602, title: "Beat Making & Hip Hop Production", description: "Sample selection, drum programming, and beat creation", level: "beginner", duration: "4.5 hours", students: 123000, rating: 4.9, tags: ["Beat Making", "Hip Hop", "Production"], icon: "🎧", category: "music" },
  { id: 603, title: "Sound Design Essentials", description: "Synthesis, sound creation, effects, and audio design", level: "intermediate", duration: "5.5 hours", students: 71000, rating: 4.8, tags: ["Sound Design", "Synthesis", "Audio"], icon: "🔊", category: "music" },
  { id: 604, title: "Music Mixing & Mastering", description: "Balance, EQ, compression, and professional master preparation", level: "intermediate", duration: "6 hours", students: 94000, rating: 4.8, tags: ["Mixing", "Mastering", "Audio Engineering"], icon: "🎚️", category: "music" },
  { id: 605, title: "Music Theory for Producers", description: "Scales, chords, progressions, and harmonic concepts", level: "beginner", duration: "4 hours", students: 112000, rating: 4.9, tags: ["Music Theory", "Composition", "Fundamentals"], icon: "🎼", category: "music" },
  { id: 606, title: "Logic Pro Masterclass", description: "Workflow, plugins, mixing, and music arrangement", level: "intermediate", duration: "5 hours", students: 78000, rating: 4.8, tags: ["Logic Pro", "DAW", "Production"], icon: "🍎", category: "music" },
  { id: 607, title: "Ableton Live Production", description: "Session view, arrangement, push controller, and live performance", level: "intermediate", duration: "5.5 hours", students: 87000, rating: 4.8, tags: ["Ableton", "DAW", "Production"], icon: "🎹", category: "music" },
  { id: 608, title: "Music Business & Licensing", description: "Publishing, royalties, distribution, and licensing deals", level: "intermediate", duration: "3.5 hours", students: 56000, rating: 4.7, tags: ["Music Business", "Licensing", "Revenue"], icon: "📜", category: "music" },

  // PHOTOGRAPHY COURSES (28)
  { id: 701, title: "Photography Fundamentals", description: "Exposure, composition, lighting, and camera settings", level: "beginner", duration: "5 hours", students: 156000, rating: 4.9, tags: ["Photography", "Fundamentals", "Camera"], icon: "📷", category: "photography" },
  { id: 702, title: "Portrait Photography Mastery", description: "Posing, lighting, backgrounds, and professional portraits", level: "intermediate", duration: "5 hours", students: 98000, rating: 4.8, tags: ["Portrait Photography", "Lighting", "Posing"], icon: "👤", category: "photography" },
  { id: 703, title: "Landscape & Nature Photography", description: "Composition, timing, weather, and outdoor techniques", level: "beginner", duration: "4 hours", students: 87000, rating: 4.8, tags: ["Landscape Photography", "Nature", "Composition"], icon: "🏞️", category: "photography" },
  { id: 704, title: "Product Photography Pro", description: "Lighting setups, styling, backgrounds, and commercial work", level: "intermediate", duration: "4.5 hours", students: 67000, rating: 4.8, tags: ["Product Photography", "Commercial", "Lighting"], icon: "📦", category: "photography" },
  { id: 705, title: "Photo Editing with Lightroom", description: "RAW processing, presets, batch editing, and workflow", level: "beginner", duration: "3.5 hours", students: 145000, rating: 4.9, tags: ["Lightroom", "Photo Editing", "Post-Processing"], icon: "🖼️", category: "photography" },
  { id: 706, title: "Advanced Photoshop Retouching", description: "Skin retouching, color grading, composite editing, and effects", level: "advanced", duration: "6 hours", students: 71000, rating: 4.8, tags: ["Photoshop", "Retouching", "Advanced"], icon: "✂️", category: "photography" },
  { id: 707, title: "Wedding Photography", description: "Planning, shooting techniques, editing, and client management", level: "intermediate", duration: "5.5 hours", students: 52000, rating: 4.8, tags: ["Wedding Photography", "Event", "Professional"], icon: "💒", category: "photography" },

  // WRITING COURSES (25)
  { id: 801, title: "Copywriting for Conversions", description: "Sales copy, persuasive writing, and psychological triggers", level: "intermediate", duration: "4 hours", students: 134000, rating: 4.9, tags: ["Copywriting", "Sales", "Marketing"], icon: "✍️", category: "writing" },
  { id: 802, title: "Content Writing Fundamentals", description: "Blog posts, articles, web copy, and editorial writing", level: "beginner", duration: "3.5 hours", students: 156000, rating: 4.9, tags: ["Content Writing", "Blogging", "Writing"], icon: "📝", category: "writing" },
  { id: 803, title: "Storytelling Mastery", description: "Narrative structure, character development, and emotional impact", level: "intermediate", duration: "5 hours", students: 98000, rating: 4.8, tags: ["Storytelling", "Narrative", "Creative Writing"], icon: "📖", category: "writing" },
  { id: 804, title: "Screenwriting for Film", description: "Story structure, dialogue, formatting, and screenplay writing", level: "intermediate", duration: "6 hours", students: 73000, rating: 4.8, tags: ["Screenwriting", "Film", "Creative"], icon: "🎬", category: "writing" },
  { id: 805, title: "Technical Writing Essentials", description: "Documentation, user guides, API docs, and clear communication", level: "intermediate", duration: "3.5 hours", students: 67000, rating: 4.8, tags: ["Technical Writing", "Documentation", "Writing"], icon: "📚", category: "writing" },
  { id: 806, title: "Email Marketing Copywriting", description: "Subject lines, body copy, CTAs, and conversion optimization", level: "intermediate", duration: "3 hours", students: 94000, rating: 4.8, tags: ["Email", "Copywriting", "Marketing"], icon: "📧", category: "writing" },
  { id: 807, title: "SEO & Blog Strategy", description: "Keyword research, optimization, content planning, and growth", level: "beginner", duration: "4 hours", students: 127000, rating: 4.9, tags: ["SEO", "Blogging", "Content Strategy"], icon: "🔍", category: "writing" },
  { id: 808, title: "Novel Writing Workshop", description: "Character creation, plot structure, dialogue, and editing", level: "intermediate", duration: "8 hours", students: 56000, rating: 4.7, tags: ["Novel Writing", "Fiction", "Creative"], icon: "📕", category: "writing" }
  ];

  export const creatorCoursesExpanded = expandedCourses.filter(c => c.category === "creator");
  export const codingCoursesExpanded = expandedCourses.filter(c => c.category === "coding");
  export const artCoursesExpanded = expandedCourses.filter(c => c.category === "art");
  export const designCoursesExpanded = expandedCourses.filter(c => c.category === "design");
  export const businessCoursesExpanded = expandedCourses.filter(c => c.category === "business");
  export const musicCoursesExpanded = expandedCourses.filter(c => c.category === "music");
  export const photographyCoursesExpanded = expandedCourses.filter(c => c.category === "photography");
  export const writingCoursesExpanded = expandedCourses.filter(c => c.category === "writing");