import { Link } from "react-router-dom";
import { ArrowLeft, BookOpen, CalendarDays, GraduationCap, HeartHandshake, Library, Map, Users, Radio, BriefcaseBusiness } from "lucide-react";

const sections=[
 {title:"Academics",detail:"Programs, course catalog, faculty, learning resources and academic policies.",icon:BookOpen,items:["Programs & fields of study","Course catalog","Faculty","Academic calendar","General & life education"]},
 {title:"Student Life",detail:"The parts of college life that live outside the course room.",icon:Users,items:["Clubs & organizations","Campus events","Study groups","Student communities","WorldChat spaces"]},
 {title:"Creator Campus",detail:"Streaming, video, creator education and the bridge from coursework into professional creator practice.",icon:Radio,to:"/Academy/CreatorCampus",items:["Student creator showcase","Live campus","Content Creator pathway","Creator communities"]},
 {title:"Careers & Industry",detail:"Prepare for professional work as a creator, manager, producer, developer, artist or other industry role.",icon:BriefcaseBusiness,items:["Career center","Creator management","Production teams","Freelancing & entrepreneurship","Industry partnerships"]},
 {title:"Student Support",detail:"Places to go when you need academic, accessibility or practical support.",icon:HeartHandshake,items:["Advising","Accessibility & accommodations","Career support","Help center"]},
 {title:"Campus & Labs",detail:"Virtual spaces and, later, partner facilities for work that needs the physical world.",icon:Map,items:["Virtual campus","Studios & labs","Partner facilities","Space reservations"]},
 {title:"Library & Resources",detail:"Course resources, guides, research material and school policies.",icon:Library,items:["Resource library","Software & tools","Policies","Student handbook"]},
 {title:"Records",detail:"Private academic information belongs in a dedicated student area.",icon:GraduationCap,items:["Academic progress","Grades & feedback","Credentials","Records & exports"]},
];
export default function AcademyExplore(){
 return <div className="min-h-[calc(100vh-4rem)] bg-[#03080f] text-white"><header className="border-b border-[#12305f]/70 bg-[#06101f]/85"><div className="mx-auto max-w-7xl px-5 py-9 sm:px-8"><Link to="/Academy" className="inline-flex items-center gap-2 text-xs font-black text-[#7ddcff]"><ArrowLeft className="h-4 w-4"/> Blue Academy</Link><p className="mt-6 text-xs font-black uppercase tracking-[.22em] text-purple-300">Explore the school</p><h1 className="mt-2 text-4xl font-black">Everything has a place.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-blue-100/55">The student home stays focused on what you need today. Deeper school information lives here and in dedicated side pages, so Academy can grow without turning the dashboard into a wall of buttons.</p></div></header>
 <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sections.map(({title,detail,icon:Icon,items,to})=><section key={title} className="rounded-2xl border border-[#12305f]/70 bg-[#06101f]/75 p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-[#1e78ff]/25 bg-[#1e78ff]/10"><Icon className="h-5 w-5 text-[#7ddcff]"/></div><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-blue-100/50">{detail}</p><div className="mt-5 space-y-2">{items.map(item=><div key={item} className="rounded-lg border border-[#12305f]/45 bg-[#03080f]/45 px-3 py-2 text-xs font-bold text-blue-100/45">{item} <span className="float-right text-white/20">building</span></div>)}</div>{to&&<Link to={to} className="mt-5 inline-flex items-center text-xs font-black text-[#00c8ff]">Open area →</Link>}{title==="Student Life"&&<Link to="/WorldChat" className="mt-5 inline-flex items-center text-xs font-black text-[#00c8ff]">Open WorldChat →</Link>}</section>)}</div>
 <section className="mt-8 rounded-2xl border border-amber-400/15 bg-amber-400/5 p-5"><div className="flex items-center gap-2 text-sm font-black text-amber-200"><CalendarDays className="h-4 w-4"/> Information architecture preview</div><p className="mt-2 text-sm leading-6 text-amber-100/55">These are navigation destinations, not claims that the offices or services are operating yet. We will turn them into real pages as their systems are built.</p></section></main></div>
}
