import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, BookOpen, PlaySquare, Radio, ShieldCheck, Sparkles, Users } from "lucide-react";

const lanes=[
 {title:"Student Creator Showcase",detail:"Finished work students choose to publish from eligible courses and portfolio projects.",icon:PlaySquare},
 {title:"Live Campus",detail:"Student and faculty streams, workshops, showcases, performances and approved campus events.",icon:Radio},
 {title:"Creator Learning",detail:"A bridge between content-creator courses and real publishing practice inside the VStream ecosystem.",icon:BookOpen},
 {title:"Communities",detail:"Creator clubs, classmates, audiences and project communities without mixing private class records into public profiles.",icon:Users},
];
export default function AcademyCreatorCampus(){
 return <div className="min-h-[calc(100vh-4rem)] bg-[#03080f] text-white"><header className="relative overflow-hidden border-b border-[#12305f]/70 bg-[#06101f]/90"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_0%,rgba(239,68,68,.14),transparent_28%),radial-gradient(circle_at_15%_0%,rgba(30,120,255,.18),transparent_30%)]"/><div className="relative mx-auto max-w-7xl px-5 py-12 sm:px-8"><Link to="/Academy" className="inline-flex items-center gap-2 text-xs font-black text-[#7ddcff]"><ArrowLeft className="h-4 w-4"/> Blue Academy</Link><div className="mt-6 inline-flex items-center gap-2 rounded-full border border-red-400/20 bg-red-400/10 px-3 py-1.5 text-xs font-black text-red-200"><Radio className="h-4 w-4"/> CREATOR CAMPUS</div><h1 className="mt-4 max-w-4xl text-4xl font-black sm:text-5xl">Learn creation, then actually create in public.</h1><p className="mt-4 max-w-3xl text-base leading-7 text-blue-100/60">Creator Campus connects Blue Academy to the streaming and video platform VStream started as. Students in creator-focused programs can practice professional workflows, build portfolios, and choose to publish eligible work without turning the classroom itself into a public feed.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/Live" className="rounded-xl bg-red-500 px-5 py-3 text-sm font-black">Browse live streams <ArrowRight className="ml-1 inline h-4 w-4"/></Link><Link to="/" className="rounded-xl border border-[#1e78ff]/40 bg-[#03080f]/60 px-5 py-3 text-sm font-black text-[#7ddcff]">Open VStream</Link></div></div></header>
 <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="grid gap-4 md:grid-cols-2">{lanes.map(({title,detail,icon:Icon})=><section key={title} className="rounded-2xl border border-[#12305f]/70 bg-[#06101f]/75 p-6"><Icon className="h-5 w-5 text-[#00c8ff]"/><h2 className="mt-4 text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-blue-100/50">{detail}</p></section>)}</div>
 <section className="mt-8 rounded-3xl border border-purple-500/20 bg-purple-500/5 p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-purple-300"><Sparkles className="h-4 w-4"/> Content Creator pathway</div><h2 className="mt-3 text-2xl font-black">Classroom → studio → portfolio → audience</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-blue-100/55">A content-creation course should not stop at theory. Students can learn planning, recording, editing, streaming, branding, moderation, analytics and creator business skills; practice in CreatorOS; submit private academic versions for grading; then separately choose what becomes portfolio or public VStream content.</p><div className="mt-5 flex flex-wrap gap-3"><Link to="/CreatorOS" className="rounded-xl border border-purple-400/30 bg-purple-400/10 px-4 py-2 text-sm font-black text-purple-200">CreatorOS</Link><Link to="/Shorts" className="rounded-xl border border-[#12305f] px-4 py-2 text-sm font-black text-blue-100/60">Videos & Shorts</Link><Link to="/Communities" className="rounded-xl border border-[#12305f] px-4 py-2 text-sm font-black text-blue-100/60">Communities</Link></div></section>
 <section className="mt-5 rounded-2xl border border-emerald-400/15 bg-emerald-400/5 p-5"><div className="flex items-center gap-2 text-sm font-black text-emerald-200"><ShieldCheck className="h-4 w-4"/> Publishing stays separate from grading</div><p className="mt-2 text-sm leading-6 text-emerald-100/55">Submitting an assignment does not publish it. Public posting is a separate creator action with its own audience, consent and visibility choices.</p></section></main></div>
}
